/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(quest)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(quest)'}/quest` | `/quest`; params?: Router.UnknownInputParams; } | { pathname: `/components/footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/header`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(quest)'}/camera` | `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(quest)'}/quest` | `/quest`; params?: Router.UnknownOutputParams; } | { pathname: `/components/footer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/header`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(profile)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(quest)'}/camera${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `${'/(quest)'}/quest${`?${string}` | `#${string}` | ''}` | `/quest${`?${string}` | `#${string}` | ''}` | `/components/footer${`?${string}` | `#${string}` | ''}` | `/components/header${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(quest)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(quest)'}/quest` | `/quest`; params?: Router.UnknownInputParams; } | { pathname: `/components/footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/header`; params?: Router.UnknownInputParams; };
    }
  }
}
